version: "1.0.0"
sambamba_bed: "project-ByfFPz00jy1fk6PjpZ95F27J:file-Gzj0Pyj0jy1VpJz3768kz8KY"
normals_RData: "project-J0Jb8Vj0Xj5JG1ZK66fjg47:file-J0Kzf3804zjJygFfFfJqXG6K"
reference_genome: "project-ByfFPz00jy1fk6PjpZ95F27J:file-B6ZY7VG2J35Vfvpkj8y0KZ01"
chanjo_sambamba_coverage: "applet-G6vyyf00jy1kPkX9PJ1YkxB1"
workflow: "project-ByfFPz00jy1fk6PjpZ95F27J:workflow-Gzj03g80jy1XbKzZY4yz7JXZ"
dnanexus_auth_token_path: "/usr/local/src/mokaguys/.dnanexus_auth_token"
cnv_applet: "project-ByfFPz00jy1fk6PjpZ95F27J:applet-GybZV0006bZFBzgf54KP7BKj"
fastqc_applet: "applet-GKXqZV80jy1QxF4yKYB4Y3Kz"
picard_applet: "applet-GQKxx1Q0jy1kFXjx5961Pb8j"
readcount_applet: "project-ByfFPz00jy1fk6PjpZ95F27J:applet-GyQGKjQ0qG6x59F4f1qBFvgz"
picard_fasta_index: "project-ByfFPz00jy1fk6PjpZ95F27J:file-ByYgX700b80gf4ZY1GxvF3Jv"
picard_vendor_exome_bedfile: "project-ByfFPz00jy1fk6PjpZ95F27J:file-Gzj07J00jy1kVJXbFj8z67G0"
common_data_project: "project-ByfFPz00jy1fk6PjpZ95F27J"
readcount_bedfile: "project-ByfFPz00jy1fk6PjpZ95F27J:/Data/BED/Pan5279_exomeDepth.bed"